pygments: true
lsi: true
permalink: /blog/:year/:month/:day/:title
exclude: [imgfac]

# Site data
#baseurl: /imagefactory
baseurl:
url: http://aeolusproject.github.com/imagefactory/
sitename: imagefactory
tagline: build, push, deploy

navigation:
- name: Home
  url: /
  section: home
- name: Blog
  url: /blog
  section: blog
- name: Documentation
  url: /documentation
  section: documentation

