safe: false
auto: true
pygments: true

# Site data
url: http://imgfac.org
sitename: imagefactory
tagline: build, push, deploy

navigation:
- name: Home
  url: /
  layout: default
- name: Blog
  url: /blog
  layout: page
- name: Documentation
  url: /docs
  layout: page
