pygments: true
lsi: true
permalink: /blog/:year/:month/:day/:title

# Site data
baseurl: /imagefactory
url: http://imgfac.org
sitename: imagefactory
tagline: build, push, deploy

navigation:
- name: Home
  url: /
  section: home
- name: Blog
  url: /blog
  section: blog
- name: Documentation
  url: /docs
  section: documentation

